### ISSUE TITLE
CRT Shader Rotation for Vertical MAME Games

### ISSUE THREAD

**Issue by Awakened0** [libretro/common-shaders#50]
Current CRT shaders don't rotate for vertically orientated games in MAME. Would it be possible to add auto detection to them so if they see a game running at something like 240x320, the scanlines and shadowmask are rotated? Or maybe a manual vertical parameter?

I've seen some discussion about a version of Lottes shader modified for vertical games in MAME here: http://www.mameworld.info/ubbthreads/showthreaded.php?Cat=&Number=331810&page=0&view=expanded&sb=5&o=&vc=1

**Comment by hizzlekizzle** [comment]
Rather than changing the shaders, it would be better for the core to handle it. FBA does it properly. Not sure why MAME doesn't.

For making crt-lottes vertical, this one should work, though it doesn't look particularly awesome that way: http://pastie.org/10219401

The thing to remember when making it vertical is that his shadow mask doesn't play nicely with being rotated because it depends on the geometry of LCD pixels, so simply rotating the whole shader won't work without modification. I had to rotate the other stuff while leaving the dotmask intact.

**Comment by fr500** [comment]
maybe it's because MAME uses a huge framebuffer underneath, it's running a framebuffer 1600x1200 IIRC

**Comment by Awakened0** [comment]
Yeah, that vertical version doesn't look any better than the normal one with a rotated game in MAME. Seems like it really is something that needs to be changed in the core. Though you'd still need a modified version of Lottes to make that one look best.

I'll close this and open an issue on the core's page.
