### ISSUE TITLE
How to debug shader loading?

### ISSUE THREAD

**Issue by madig** [libretro/common-shaders#84]
I'm using RA from master on Fedora 24. I've noticed that there are many shaders (from the GLSL package downloaded via the updater) that upon loading.. do nothing. `fx-aa.glsl` is one example. However, running `retroarch --verbose` doesn't produce any errors regarding shader loading. Is there some way to find out why the shader doesn't load?

**Comment by hizzlekizzle** [comment]
If there are no errors in the verbose log, it means it's compiling successfully and just isn't really doing anything (nothing visible, at least). This is difficult to debug because the script-converted GLSL shaders are horrible spaghetti code. The options in cases like this are basically: use the Cg version, hand-convert from Cg to GLSL, hand-write a GLSL version (luckily, FXAA is available elsewhere in GLSL, so this is actually a fair possibility) or wait until we get spir-v reflection to produce a better automated conversion (I haven't actually made a slang version of FXAA yet but was planning to do one soon).

**Comment by madig** [comment]
Hm, I'd use the Cg version, but the log says `RetroArch [ERROR] :: [Shader driver]: Cg cannot be used with core GL context. Trying to fall back to GLSL...` :( Oh well, thanks anyway, I'll go look for a GLSL version.

**Comment by hizzlekizzle** [comment]
Ah, ok. IIRC, that error is usually related to the ribbon effect in the menu. You could try turning it off in settings > menu to see if that helps.

**Comment by madig** [comment]
The ribbon was turned off already.

**Comment by madig** [comment]
(Interestingly, the `fx-aa.cg` shader (Cg!)  didn't to anything visible either on Windows. Hm.)

**Comment by hizzlekizzle** [comment]
That is interesting. I thought I remembered that one working properly...

I just ported a version to slang and it works pretty well, if you can run the vulkan context (won't work with mupen, reicast or ppsspp)

**Comment by madig** [comment]
That one works. Guess I'll wait for SPIR-V reflection :)
